version: "3.2"
services:
  tester:
    image: <%= @project_repo %>/<%= @project_name %>:<%= @tag %>
    
    build:
      context: ..

    depends_on:
      - <%= @project_name%>-db
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgres://test:test@<%=@project_name%>-db/testdb?pool=5
      - HOST=<%=@project_name%>-test.fixingthe.net
      - BASE_DOMAIN=<%=@project_name%>-test.fixingthe.net
<% @opts.each_pair do |k,v| %>
      - <%= k %>=<%= v%>

<% end %>
<% unless @volumes.empty?  %>      
    volumes:
<% @volumes.each do |v| %>
      - <%= v %>
<% end %>
<% end %>

    command:
      "bin/run_tests"
  <%=@project_name%>-db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
